/**
 * locations.c
 * -----------
 * Contains the tables for entrances, exits, holes, and connections declared in the header.
 *
 * These tables were partially generated using data in the Archipelago Multiworld repo here:
 * https://github.com/ArchipelagoMW/Archipelago/tree/main/worlds/alttp, especially EntranceShuffle.py and Rom.py.
 *
 * Those partially generated tables were then used to run a script against a vanilla ALttP (JP v1.0) ROM to generate
 * the full tables. Region properties and the region_links table were added manually to support region-to-region
 * connections.
 */

#include "locations.h"

const char *region_to_str(
    const enum region region) {
    switch (region) {
        case REGION_EXT_LW_OVERWORLD: return "Light World Overworld";
        case REGION_EXT_LW_DEATH_MOUNTAIN_LOWER: return "Light World Death Mountain (Lower)";
        case REGION_EXT_LW_DEATH_MOUNTAIN_UPPER: return "Light World Death Mountain (Upper)";
        case REGION_EXT_LW_DEATH_MOUNTAIN_SPECTACLE_ROCK_CAVE_LOWER: return "Light World Death Mountain Spectacle Rock Cave (Lower)";
        case REGION_EXT_LW_DEATH_MOUNTAIN_SPECTACLE_ROCK_CAVE_MID: return "Light World Death Mountain Spectacle Rock Cave (Mid)";
        case REGION_EXT_LW_DEATH_MOUNTAIN_SPIRAL_CAVE_TOP:  return "Light World Death Mountain Spiral Cave (Top)";
        case REGION_EXT_LW_DEATH_MOUNTAIN_FAIRY_ASCENSION_CAVE_TOP: return "Light World Death Mountain Fairy Ascension Cave (Top)";
        case REGION_EXT_LW_DEATH_MOUNTAIN_MIMIC_CAVE_LEDGE: return "Light World Death Mountain Mimic Cave Ledge";
        case REGION_EXT_LW_DEATH_MOUNTAIN_RETURN_LEDGE: return "Light World Death Mountain Return Ledge";
        case REGION_EXT_LW_LOST_WOODS:  return "Light World Lost Woods";
        case REGION_EXT_LW_HYRULE_CASTLE_ROOF: return "Light World Hyrule Castle Roof";
        case REGION_EXT_LW_DESERT_PALACE_LEDGE: return "Light World Desert Palace Ledge";
        case REGION_EXT_LW_DESERT_PALACE_EAST: return "Light World Desert Palace (East)";
        case REGION_EXT_LW_CAVE_45_LEDGE: return "Light World Cave 45 Ledge";
        case REGION_EXT_LW_CHECKERBOARD_CAVE_LEDGE: return "Light World Checkerboard Cave Ledge";
        case REGION_EXT_LW_GRAVEYARD_CAVE_LEDGE: return "Light World Graveyard Cave Ledge";

        case REGION_EXT_DW_OVERWORLD: return "Dark World Overworld";
        case REGION_EXT_DW_MIRE: return "Dark World Mire";
        case REGION_EXT_DW_BUMPER_CAVE_TOP: return "Dark World Bumper Cave (Top)";
        case REGION_EXT_DW_DEATH_MOUNTAIN_LOWER_EAST: return "Dark World Death Mountain (Lower, East)";
        case REGION_EXT_DW_DEATH_MOUNTAIN_LOWER_WEST: return "Dark World Death Mountain (Lower, West)";
        case REGION_EXT_DW_DEATH_MOUNTAIN_UPPER: return "Dark World Death Mountain (Upper)";
        case REGION_EXT_DW_DEATH_MOUNTAIN_FLOATING_LEDGE: return "Dark World Death Mountain Floating Ledge";
        case REGION_EXT_DW_DEATH_MOUNTAIN_TURTLE_ROCK_LONG_LEDGE: return "Dark World Death Mountain Turtle Rock Long Ledge";
        case REGION_EXT_DW_DEATH_MOUNTAIN_TURTLE_ROCK_ISOLATED_LEDGE: return "Dark World Death Mountain Turtle Rock Isolated Ledge";
        case REGION_EXT_DW_DEATH_MOUNTAIN_SPIKE_CAVE_LEDGE: return "Dark World Death Mountain Spike Cave Ledge";
        case REGION_EXT_DW_LOST_WOODS_SOUTH: return "Dark World Lost Woods (South)";
        case REGION_EXT_DW_LOST_WOODS_NORTH: return "Dark World Lost Woods (North)";
        case REGION_EXT_DW_OUTSIDE_ICE_PALACE: return "Dark World Outside Ice Palace";

        case REGION_INT_LW_ELDER_HOUSE: return "Light World Elder House";
        case REGION_INT_LW_TWO_BROTHERS_HOUSE: return "Light World Two Brothers House";
        case REGION_INT_LW_DEATH_MOUNTAIN_OLD_MAN_CAVE: return "Light World Death Mountain Old Man Cave";
        case REGION_INT_LW_DEATH_MOUNTAIN_OLD_MAN_HOUSE: return "Light World Death Mountain Old Man House";
        case REGION_INT_LW_DEATH_MOUNTAIN_RETURN_CAVE: return "Light World Death Mountain Return Cave";
        case REGION_INT_LW_DEATH_MOUNTAIN_PARADOX_CAVE: return "Light World Death Mountain Paradox Cave";
        case REGION_INT_LW_DEATH_MOUNTAIN_SPECTACLE_ROCK_CAVE_LOWER: return "Light World Death Mountain Spectacle Rock Cave (Lower)";
        case REGION_INT_LW_DEATH_MOUNTAIN_SPECTACLE_ROCK_CAVE_MID: return "Light World Death Mountain Spectacle Rock Cave (Mid)";
        case REGION_INT_LW_DEATH_MOUNTAIN_SPECTACLE_ROCK_CAVE_PEAK: return "Light World Death Mountain Spectacle Rock Cave (Peak)";
        case REGION_INT_LW_DEATH_MOUNTAIN_SPIRAL_CAVE_UPPER: return "Light World Death Mountain Spiral Cave (Upper)";
        case REGION_INT_LW_DEATH_MOUNTAIN_SPIRAL_CAVE_LOWER: return "Light World Death Mountain Spiral Cave (Lower)";
        case REGION_INT_LW_DEATH_MOUNTAIN_FAIRY_ASCENSION_CAVE: return "Light World Death Mountain Fairy Ascension Cave";
        case REGION_INT_LW_HYRULE_CASTLE: return "Light World Hyrule Castle";
        case REGION_INT_LW_SANCTUARY: return "Light World Sanctuary";
        case REGION_INT_LW_DESERT_PALACE_FIRST_PART: return "Desert Palace (First Part)";

        case REGION_INT_DW_BUMPER_CAVE: return "Dark World Bumper Cave";
        case REGION_INT_DW_DEATH_MOUNTAIN_HOOKSHOT_CAVE: return "Dark World Death Mountain Hookshot Cave";
        case REGION_INT_DW_DEATH_MOUNTAIN_SUPERBUNNY_CAVE_LOWER: return "Dark World Death Mountain Superbunny Cave (Lower)";
        case REGION_INT_DW_DEATH_MOUNTAIN_SUPERBUNNY_CAVE_UPPER: return "Dark World Death Mountain Superbunny Cave (Upper)";
        case REGION_INT_DW_SKULL_WOODS_SECOND_SECTION: return "Skull Woods (Second Part)";
        case REGION_INT_DW_TURTLE_ROCK: return "Turtle Rock";

        default: return "Unknown";
    }
}

const entrance entrances[] = {
    {
        .name = "20 Rupee Cave",
        .target_offset = 0xdbbed,
        .vanilla_target_value = 0x6f,
        .vanilla_exterior_region = REGION_EXT_LW_OVERWORLD,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "50 Rupee Cave",
        .target_offset = 0xdbbeb,
        .vanilla_target_value = 0x6d,
        .vanilla_exterior_region = REGION_EXT_LW_OVERWORLD,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "Agahnims Tower",
        .target_offset = 0xdbb96,
        .vanilla_target_value = 0x24,
        .vanilla_exterior_region = REGION_EXT_LW_HYRULE_CASTLE_ROOF,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "Aginahs Cave",
        .target_offset = 0xdbbe3,
        .vanilla_target_value = 0x4d,
        .vanilla_exterior_region = REGION_EXT_LW_OVERWORLD,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "Archery Game",
        .target_offset = 0xdbbcb,
        .vanilla_target_value = 0x59,
        .vanilla_exterior_region = REGION_EXT_DW_OVERWORLD,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "Bat Cave Cave",
        .target_offset = 0xdbb83,
        .vanilla_target_value = 0x11,
        .vanilla_exterior_region = REGION_EXT_LW_OVERWORLD,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "Big Bomb Shop",
        .target_offset = 0xdbbc5,
        .vanilla_target_value = 0x53,
        .vanilla_exterior_region = REGION_EXT_DW_OVERWORLD,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "Blacksmiths Hut",
        .target_offset = 0xdbbd6,
        .vanilla_target_value = 0x64,
        .vanilla_exterior_region = REGION_EXT_LW_OVERWORLD,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "Blinds Hideout",
        .target_offset = 0xdbbd3,
        .vanilla_target_value = 0x61,
        .vanilla_exterior_region = REGION_EXT_LW_OVERWORLD,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "Bonk Fairy (Dark)",
        .target_offset = 0xdbbea,
        .vanilla_target_value = 0x71,
        .vanilla_exterior_region = REGION_EXT_DW_OVERWORLD,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "Bonk Fairy (Light)",
        .target_offset = 0xdbbe9,
        .vanilla_target_value = 0x71,
        .vanilla_exterior_region = REGION_EXT_LW_OVERWORLD,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "Bonk Rock Cave",
        .target_offset = 0xdbbec,
        .vanilla_target_value = 0x6e,
        .vanilla_exterior_region = REGION_EXT_LW_OVERWORLD,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "Brewery",
        .target_offset = 0xdbbba,
        .vanilla_target_value = 0x48,
        .vanilla_exterior_region = REGION_EXT_DW_OVERWORLD,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "Bumper Cave (Bottom)",
        .target_offset = 0xdbb88,
        .vanilla_target_value = 0x16,
        .vanilla_exterior_region = REGION_EXT_DW_OVERWORLD,
        .vanilla_interior_region = REGION_INT_DW_BUMPER_CAVE,
    },
    {
        .name = "Bumper Cave (Top)",
        .target_offset = 0xdbb89,
        .vanilla_target_value = 0x17,
        .vanilla_exterior_region = REGION_EXT_DW_BUMPER_CAVE_TOP,
        .vanilla_interior_region = REGION_INT_DW_BUMPER_CAVE,
    },
    {
        .name = "Bush Covered House",
        .target_offset = 0xdbbb6,
        .vanilla_target_value = 0x44,
        .vanilla_exterior_region = REGION_EXT_LW_OVERWORLD,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "C-Shaped House",
        .target_offset = 0xdbbc6,
        .vanilla_target_value = 0x54,
        .vanilla_exterior_region = REGION_EXT_DW_OVERWORLD,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "Capacity Upgrade",
        .target_offset = 0xdbbcf,
        .vanilla_target_value = 0x5d,
        .vanilla_exterior_region = REGION_EXT_LW_OVERWORLD,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "Cave 45",
        .target_offset = 0xdbbc3,
        .vanilla_target_value = 0x51,
        .vanilla_exterior_region = REGION_EXT_LW_CAVE_45_LEDGE,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "Cave Shop (Dark Death Mountain)",
        .target_offset = 0xdbbe0,
        .vanilla_target_value = 0x58,
        .vanilla_exterior_region = REGION_EXT_DW_DEATH_MOUNTAIN_LOWER_EAST,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "Cave Shop (Lake Hylia)",
        .target_offset = 0xdbbca,
        .vanilla_target_value = 0x58,
        .vanilla_exterior_region = REGION_EXT_LW_OVERWORLD,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "Checkerboard Cave",
        .target_offset = 0xdbbf0,
        .vanilla_target_value = 0x72,
        .vanilla_exterior_region = REGION_EXT_LW_CHECKERBOARD_CAVE_LEDGE,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "Chest Game",
        .target_offset = 0xdbbb9,
        .vanilla_target_value = 0x47,
        .vanilla_exterior_region = REGION_EXT_DW_OVERWORLD,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "Chicken House",
        .target_offset = 0xdbbbd,
        .vanilla_target_value = 0x4b,
        .vanilla_exterior_region = REGION_EXT_LW_OVERWORLD,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "Dam",
        .target_offset = 0xdbbc0,
        .vanilla_target_value = 0x4e,
        .vanilla_exterior_region = REGION_EXT_LW_OVERWORLD,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "Dark Death Mountain Fairy",
        .target_offset = 0xdbbe2,
        .vanilla_target_value = 0x5e,
        .vanilla_exterior_region = REGION_EXT_DW_DEATH_MOUNTAIN_LOWER_WEST,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "Turtle Rock Ledge (East)",
        .target_offset = 0xdbb8b,
        .vanilla_target_value = 0x19,
        .vanilla_exterior_region = REGION_EXT_DW_DEATH_MOUNTAIN_TURTLE_ROCK_LONG_LEDGE,
        .vanilla_interior_region = REGION_INT_DW_TURTLE_ROCK,
    },
    {
        .name = "Turtle Rock Ledge (West)",
        .target_offset = 0xdbb87,
        .vanilla_target_value = 0x15,
        .vanilla_exterior_region = REGION_EXT_DW_DEATH_MOUNTAIN_TURTLE_ROCK_LONG_LEDGE,
        .vanilla_interior_region = REGION_INT_DW_TURTLE_ROCK,
    },
    {
        .name = "Dark Desert Fairy",
        .target_offset = 0xdbbc8,
        .vanilla_target_value = 0x5e,
        .vanilla_exterior_region = REGION_EXT_DW_MIRE,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "Dark Desert Hint",
        .target_offset = 0xdbbd4,
        .vanilla_target_value = 0x62,
        .vanilla_exterior_region = REGION_EXT_DW_MIRE,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "Dark Lake Hylia Fairy",
        .target_offset = 0xdbbdf,
        .vanilla_target_value = 0x5e,
        .vanilla_exterior_region = REGION_EXT_DW_OVERWORLD,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "Dark Lake Hylia Ledge Fairy",
        .target_offset = 0xdbbf3,
        .vanilla_target_value = 0x5e,
        .vanilla_exterior_region = REGION_EXT_DW_OVERWORLD,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "Dark Lake Hylia Ledge Hint",
        .target_offset = 0xdbbdc,
        .vanilla_target_value = 0x6a,
        .vanilla_exterior_region = REGION_EXT_DW_OVERWORLD,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "Dark Lake Hylia Ledge Spike Cave",
        .target_offset = 0xdbbee,
        .vanilla_target_value = 0x70,
        .vanilla_exterior_region = REGION_EXT_DW_OVERWORLD,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "Dark Lake Hylia Shop",
        .target_offset = 0xdbbe6,
        .vanilla_target_value = 0x60,
        .vanilla_exterior_region = REGION_EXT_DW_OVERWORLD,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "Dark Sanctuary Hint",
        .target_offset = 0xdbbcc,
        .vanilla_target_value = 0x5a,
        .vanilla_exterior_region = REGION_EXT_DW_OVERWORLD,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "Dark World Hammer Peg Cave",
        .target_offset = 0xdbbf1,
        .vanilla_target_value = 0x83,
        .vanilla_exterior_region = REGION_EXT_DW_OVERWORLD,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "Dark World Lumberjack Shop",
        .target_offset = 0xdbbc9,
        .vanilla_target_value = 0x60,
        .vanilla_exterior_region = REGION_EXT_DW_OVERWORLD,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "Dark World Potion Shop",
        .target_offset = 0xdbbe1,
        .vanilla_target_value = 0x60,
        .vanilla_exterior_region = REGION_EXT_DW_OVERWORLD,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "Death Mountain Return Cave (East)",
        .target_offset = 0xdbba1,
        .vanilla_target_value = 0x2f,
        .vanilla_exterior_region = REGION_EXT_LW_DEATH_MOUNTAIN_LOWER,
        .vanilla_interior_region = REGION_INT_LW_DEATH_MOUNTAIN_RETURN_CAVE,
    },
    {
        .name = "Death Mountain Return Cave (West)",
        .target_offset = 0xdbba0,
        .vanilla_target_value = 0x2e,
        .vanilla_exterior_region = REGION_EXT_LW_DEATH_MOUNTAIN_RETURN_LEDGE,
        .vanilla_interior_region = REGION_INT_LW_DEATH_MOUNTAIN_RETURN_CAVE,
    },
    {
        .name = "Desert Fairy",
        .target_offset = 0xdbbe4,
        .vanilla_target_value = 0x5e,
        .vanilla_exterior_region = REGION_EXT_LW_OVERWORLD,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "Desert Palace (East)",
        .target_offset = 0xdbb7c,
        .vanilla_target_value = 0xa,
        .vanilla_exterior_region = REGION_EXT_LW_DESERT_PALACE_EAST,
        .vanilla_interior_region = REGION_INT_LW_DESERT_PALACE_FIRST_PART,
    },
    {
        .name = "Desert Palace (North)",
        .target_offset = 0xdbb7e,
        .vanilla_target_value = 0xc,
        .vanilla_exterior_region = REGION_EXT_LW_DESERT_PALACE_LEDGE,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "Desert Palace (South)",
        .target_offset = 0xdbb7b,
        .vanilla_target_value = 0x9,
        .vanilla_exterior_region = REGION_EXT_LW_OVERWORLD,
        .vanilla_interior_region = REGION_INT_LW_DESERT_PALACE_FIRST_PART,
    },
    {
        .name = "Desert Palace (West)",
        .target_offset = 0xdbb7d,
        .vanilla_target_value = 0xb,
        .vanilla_exterior_region = REGION_EXT_LW_DESERT_PALACE_LEDGE,
        .vanilla_interior_region = REGION_INT_LW_DESERT_PALACE_FIRST_PART,
    },
    {
        .name = "East Dark World Hint",
        .target_offset = 0xdbbdb,
        .vanilla_target_value = 0x69,
        .vanilla_exterior_region = REGION_EXT_DW_OVERWORLD,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "Eastern Palace",
        .target_offset = 0xdbb7a,
        .vanilla_target_value = 0x8,
        .vanilla_exterior_region = REGION_EXT_LW_OVERWORLD,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "Elder House (East)",
        .target_offset = 0xdbb80,
        .vanilla_target_value = 0xe,
        .vanilla_exterior_region = REGION_EXT_LW_OVERWORLD,
        .vanilla_interior_region = REGION_INT_LW_ELDER_HOUSE,
    },
    {
        .name = "Elder House (West)",
        .target_offset = 0xdbb7f,
        .vanilla_target_value = 0xd,
        .vanilla_exterior_region = REGION_EXT_LW_OVERWORLD,
        .vanilla_interior_region = REGION_INT_LW_ELDER_HOUSE,
    },
    {
        .name = "Fairy Ascension Cave (Bottom)",
        .target_offset = 0xdbb8c,
        .vanilla_target_value = 0x1a,
        .vanilla_exterior_region = REGION_EXT_LW_DEATH_MOUNTAIN_LOWER,
        .vanilla_interior_region = REGION_INT_LW_DEATH_MOUNTAIN_FAIRY_ASCENSION_CAVE,
    },
    {
        .name = "Fairy Ascension Cave (Top)",
        .target_offset = 0xdbb8d,
        .vanilla_target_value = 0x1b,
        .vanilla_exterior_region = REGION_EXT_LW_DEATH_MOUNTAIN_FAIRY_ASCENSION_CAVE_TOP,
        .vanilla_interior_region = REGION_INT_LW_DEATH_MOUNTAIN_FAIRY_ASCENSION_CAVE,
    },
    {
        .name = "Fortune Teller (Dark)",
        .target_offset = 0xdbbd8,
        .vanilla_target_value = 0x66,
        .vanilla_exterior_region = REGION_EXT_DW_OVERWORLD,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "Fortune Teller (Light)",
        .target_offset = 0xdbbd7,
        .vanilla_target_value = 0x65,
        .vanilla_exterior_region = REGION_EXT_LW_OVERWORLD,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "Ganons Tower",
        .target_offset = 0xdbba9,
        .vanilla_target_value = 0x37,
        .vanilla_exterior_region = REGION_EXT_DW_DEATH_MOUNTAIN_UPPER,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "Good Bee Cave",
        .target_offset = 0xdbbdd,
        .vanilla_target_value = 0x56,
        .vanilla_exterior_region = REGION_EXT_LW_OVERWORLD,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "Graveyard Cave",
        .target_offset = 0xdbbc4,
        .vanilla_target_value = 0x52,
        .vanilla_exterior_region = REGION_EXT_LW_GRAVEYARD_CAVE_LEDGE,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "Hookshot Cave (South)",
        .target_offset = 0xdbbac,
        .vanilla_target_value = 0x3a,
        .vanilla_exterior_region = REGION_EXT_DW_DEATH_MOUNTAIN_UPPER,
        .vanilla_interior_region = REGION_INT_DW_DEATH_MOUNTAIN_HOOKSHOT_CAVE,
    },
    {
        .name = "Hookshot Cave (North)",
        .target_offset = 0xdbbad,
        .vanilla_target_value = 0x3b,
        .vanilla_exterior_region = REGION_EXT_DW_DEATH_MOUNTAIN_FLOATING_LEDGE,
        .vanilla_interior_region = REGION_INT_DW_DEATH_MOUNTAIN_HOOKSHOT_CAVE,
    },
    {
        .name = "Hookshot Fairy",
        .target_offset = 0xdbbc2,
        .vanilla_target_value = 0x50,
        .vanilla_exterior_region = REGION_EXT_LW_DEATH_MOUNTAIN_LOWER,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "Hype Cave",
        .target_offset = 0xdbbaf,
        .vanilla_target_value = 0x3d,
        .vanilla_exterior_region = REGION_EXT_DW_OVERWORLD,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "Hyrule Castle (East)",
        .target_offset = 0xdbb77,
        .vanilla_target_value = 0x5,
        .vanilla_exterior_region = REGION_EXT_LW_HYRULE_CASTLE_ROOF,
        .vanilla_interior_region = REGION_INT_LW_HYRULE_CASTLE,
    },
    {
        .name = "Hyrule Castle (South)",
        .target_offset = 0xdbb76,
        .vanilla_target_value = 0x4,
        .vanilla_exterior_region = REGION_EXT_LW_OVERWORLD,
        .vanilla_interior_region = REGION_INT_LW_HYRULE_CASTLE,
    },
    {
        .name = "Hyrule Castle (West)",
        .target_offset = 0xdbb75,
        .vanilla_target_value = 0x3,
        .vanilla_exterior_region = REGION_EXT_LW_HYRULE_CASTLE_ROOF,
        .vanilla_interior_region = REGION_INT_LW_HYRULE_CASTLE,
    },
    {
        .name = "Hyrule Castle Secret Entrance",
        .target_offset = 0xdbba4,
        .vanilla_target_value = 0x32,
        .vanilla_exterior_region = REGION_EXT_LW_OVERWORLD,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "Ice Palace",
        .target_offset = 0xdbb9f,
        .vanilla_target_value = 0x2d,
        .vanilla_exterior_region = REGION_EXT_DW_OUTSIDE_ICE_PALACE,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "Ice Rod Cave",
        .target_offset = 0xdbbf2,
        .vanilla_target_value = 0x84,
        .vanilla_exterior_region = REGION_EXT_LW_OVERWORLD,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "Kakariko Gamble Game",
        .target_offset = 0xdbbd9,
        .vanilla_target_value = 0x67,
        .vanilla_exterior_region = REGION_EXT_LW_OVERWORLD,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "Kakariko Shop",
        .target_offset = 0xdbbb8,
        .vanilla_target_value = 0x46,
        .vanilla_exterior_region = REGION_EXT_LW_OVERWORLD,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "Kakariko Well Cave",
        .target_offset = 0xdbbab,
        .vanilla_target_value = 0x39,
        .vanilla_exterior_region = REGION_EXT_LW_OVERWORLD,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "Kings Grave",
        .target_offset = 0xdbbcd,
        .vanilla_target_value = 0x5b,
        .vanilla_exterior_region = REGION_EXT_LW_OVERWORLD,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "Lake Hylia Fairy",
        .target_offset = 0xdbbd0,
        .vanilla_target_value = 0x5e,
        .vanilla_exterior_region = REGION_EXT_LW_OVERWORLD,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "Lake Hylia Fortune Teller",
        .target_offset = 0xdbbe5,
        .vanilla_target_value = 0x65,
        .vanilla_exterior_region = REGION_EXT_LW_OVERWORLD,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "Library",
        .target_offset = 0xdbbbb,
        .vanilla_target_value = 0x49,
        .vanilla_exterior_region = REGION_EXT_LW_OVERWORLD,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "Light Hype Fairy",
        .target_offset = 0xdbbde,
        .vanilla_target_value = 0x5e,
        .vanilla_exterior_region = REGION_EXT_LW_OVERWORLD,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "Light World Bomb Hut",
        .target_offset = 0xdbbbc,
        .vanilla_target_value = 0x4a,
        .vanilla_exterior_region = REGION_EXT_LW_OVERWORLD,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "Links House",
        .target_offset = 0xdbb73,
        .vanilla_target_value = 0x1,
        .vanilla_exterior_region = REGION_EXT_LW_OVERWORLD,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "Long Fairy Cave",
        .target_offset = 0xdbbc7,
        .vanilla_target_value = 0x55,
        .vanilla_exterior_region = REGION_EXT_LW_OVERWORLD,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "Lost Woods Gamble",
        .target_offset = 0xdbbae,
        .vanilla_target_value = 0x3c,
        .vanilla_exterior_region = REGION_EXT_LW_LOST_WOODS,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "Lost Woods Hideout Stump",
        .target_offset = 0xdbb9e,
        .vanilla_target_value = 0x2c,
        .vanilla_exterior_region = REGION_EXT_LW_LOST_WOODS,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "Lumberjack House",
        .target_offset = 0xdbbe8,
        .vanilla_target_value = 0x6b,
        .vanilla_exterior_region = REGION_EXT_LW_OVERWORLD,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "Lumberjack Tree Cave",
        .target_offset = 0xdbb84,
        .vanilla_target_value = 0x12,
        .vanilla_exterior_region = REGION_EXT_LW_OVERWORLD,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "Mimic Cave",
        .target_offset = 0xdbbc1,
        .vanilla_target_value = 0x4f,
        .vanilla_exterior_region = REGION_EXT_LW_DEATH_MOUNTAIN_MIMIC_CAVE_LEDGE,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "Mini Moldorm Cave",
        .target_offset = 0xdbbef,
        .vanilla_target_value = 0x6c,
        .vanilla_exterior_region = REGION_EXT_LW_OVERWORLD,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "Mire Shed",
        .target_offset = 0xdbbd1,
        .vanilla_target_value = 0x5f,
        .vanilla_exterior_region = REGION_EXT_DW_MIRE,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "Misery Mire",
        .target_offset = 0xdbb99,
        .vanilla_target_value = 0x27,
        .vanilla_exterior_region = REGION_EXT_DW_MIRE,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "North Fairy Cave",
        .target_offset = 0xdbbaa,
        .vanilla_target_value = 0x38,
        .vanilla_exterior_region = REGION_EXT_LW_OVERWORLD, // todo: ???
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "Old Man Cave (East)",
        .target_offset = 0xdbb79,
        .vanilla_target_value = 0x7,
        .vanilla_exterior_region = REGION_EXT_LW_DEATH_MOUNTAIN_LOWER,
        .vanilla_interior_region = REGION_INT_LW_DEATH_MOUNTAIN_OLD_MAN_CAVE,
    },
    {
        .name = "Old Man Cave (West)",
        .target_offset = 0xdbb78,
        .vanilla_target_value = 0x6,
        .vanilla_exterior_region = REGION_EXT_LW_OVERWORLD,
        .vanilla_interior_region = REGION_INT_LW_DEATH_MOUNTAIN_OLD_MAN_CAVE,
    },
    {
        .name = "Old Man House (Bottom)",
        .target_offset = 0xdbba2,
        .vanilla_target_value = 0x30,
        .vanilla_exterior_region = REGION_EXT_LW_DEATH_MOUNTAIN_LOWER,
        .vanilla_interior_region = REGION_INT_LW_DEATH_MOUNTAIN_OLD_MAN_HOUSE,
    },
    {
        .name = "Old Man House (Top)",
        .target_offset = 0xdbba3,
        .vanilla_target_value = 0x31,
        .vanilla_exterior_region = REGION_EXT_LW_DEATH_MOUNTAIN_LOWER,
        .vanilla_interior_region = REGION_INT_LW_DEATH_MOUNTAIN_OLD_MAN_HOUSE,
    },
    {
        .name = "Palace of Darkness",
        .target_offset = 0xdbb98,
        .vanilla_target_value = 0x26,
        .vanilla_exterior_region = REGION_EXT_DW_OVERWORLD,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "Palace of Darkness Hint",
        .target_offset = 0xdbbda,
        .vanilla_target_value = 0x68,
        .vanilla_exterior_region = REGION_EXT_DW_OVERWORLD,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "Paradox Cave (Bottom)",
        .target_offset = 0xdbb90,
        .vanilla_target_value = 0x1e,
        .vanilla_exterior_region = REGION_EXT_LW_DEATH_MOUNTAIN_LOWER,
        .vanilla_interior_region = REGION_INT_LW_DEATH_MOUNTAIN_PARADOX_CAVE,
    },
    {
        .name = "Paradox Cave (Middle)",
        .target_offset = 0xdbb91,
        .vanilla_target_value = 0x1f,
        .vanilla_exterior_region = REGION_EXT_LW_DEATH_MOUNTAIN_LOWER,
        .vanilla_interior_region = REGION_INT_LW_DEATH_MOUNTAIN_PARADOX_CAVE,
    },
    {
        .name = "Paradox Cave (Top)",
        .target_offset = 0xdbb92,
        .vanilla_target_value = 0x20,
        .vanilla_exterior_region = REGION_EXT_LW_DEATH_MOUNTAIN_UPPER,
        .vanilla_interior_region = REGION_INT_LW_DEATH_MOUNTAIN_PARADOX_CAVE,
    },
    {
        .name = "Potion Shop",
        .target_offset = 0xdbbbe,
        .vanilla_target_value = 0x4c,
        .vanilla_exterior_region = REGION_EXT_LW_OVERWORLD,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "Pyramid (Ganon)",
        .target_offset = 0xdbba8,
        .vanilla_target_value = 0x36,
        .vanilla_exterior_region = REGION_EXT_DW_OVERWORLD,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "Pyramid Fairy",
        .target_offset = 0xdbbd5,
        .vanilla_target_value = 0x63,
        .vanilla_exterior_region = REGION_EXT_DW_OVERWORLD,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "Red Shield Shop",
        .target_offset = 0xdbbe7,
        .vanilla_target_value = 0x57,
        .vanilla_exterior_region = REGION_EXT_DW_OVERWORLD,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "Sahasrahlas Hut",
        .target_offset = 0xdbbb7,
        .vanilla_target_value = 0x45,
        .vanilla_exterior_region = REGION_EXT_LW_OVERWORLD,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "Sanctuary",
        .target_offset = 0xdbb74,
        .vanilla_target_value = 0x2,
        .vanilla_exterior_region = REGION_EXT_LW_OVERWORLD,
        .vanilla_interior_region = REGION_INT_LW_SANCTUARY,
    },
    {
        .name = "Sick Kids House",
        .target_offset = 0xdbbb2,
        .vanilla_target_value = 0x40,
        .vanilla_exterior_region = REGION_EXT_LW_OVERWORLD,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "Skull Woods Final Section",
        .target_offset = 0xdbb9d,
        .vanilla_target_value = 0x2b,
        .vanilla_exterior_region = REGION_EXT_DW_LOST_WOODS_NORTH,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "Skull Woods First Section",
        .target_offset = 0xdbb9c,
        .vanilla_target_value = 0x2a,
        .vanilla_exterior_region = REGION_EXT_DW_LOST_WOODS_SOUTH,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "Skull Woods Second Section (East)",
        .target_offset = 0xdbb9b,
        .vanilla_target_value = 0x29,
        .vanilla_exterior_region = REGION_EXT_DW_LOST_WOODS_SOUTH,
        .vanilla_interior_region = REGION_INT_DW_SKULL_WOODS_SECOND_SECTION,
    },
    {
        .name = "Skull Woods Second Section (West)",
        .target_offset = 0xdbb9a,
        .vanilla_target_value = 0x28,
        .vanilla_exterior_region = REGION_EXT_DW_LOST_WOODS_NORTH,
        .vanilla_interior_region = REGION_INT_DW_SKULL_WOODS_SECOND_SECTION,
    },
    {
        .name = "Snitch Lady (East)",
        .target_offset = 0xdbbb0,
        .vanilla_target_value = 0x3e,
        .vanilla_exterior_region = REGION_EXT_LW_OVERWORLD,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "Snitch Lady (West)",
        .target_offset = 0xdbbb1,
        .vanilla_target_value = 0x3f,
        .vanilla_exterior_region = REGION_EXT_LW_OVERWORLD,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "Spectacle Rock Cave (Mid)",
        .target_offset = 0xdbb94,
        .vanilla_target_value = 0x22,
        .vanilla_exterior_region = REGION_EXT_LW_DEATH_MOUNTAIN_SPECTACLE_ROCK_CAVE_MID,
        .vanilla_interior_region = REGION_INT_LW_DEATH_MOUNTAIN_SPECTACLE_ROCK_CAVE_MID,
    },
    {
        .name = "Spectacle Rock Cave (Bottom)",
        .target_offset = 0xdbb93,
        .vanilla_target_value = 0x21,
        .vanilla_exterior_region = REGION_EXT_LW_DEATH_MOUNTAIN_SPECTACLE_ROCK_CAVE_LOWER,
        .vanilla_interior_region = REGION_INT_LW_DEATH_MOUNTAIN_SPECTACLE_ROCK_CAVE_LOWER,
    },
    {
        .name = "Spectacle Rock Cave (Peak)",
        .target_offset = 0xdbb95,
        .vanilla_target_value = 0x23,
        .vanilla_exterior_region = REGION_EXT_LW_DEATH_MOUNTAIN_LOWER,
        .vanilla_interior_region = REGION_INT_LW_DEATH_MOUNTAIN_SPECTACLE_ROCK_CAVE_PEAK,
    },
    {
        .name = "Spike Cave",
        .target_offset = 0xdbbb3,
        .vanilla_target_value = 0x41,
        .vanilla_exterior_region = REGION_EXT_DW_DEATH_MOUNTAIN_SPIKE_CAVE_LEDGE,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "Spiral Cave (Top)",
        .target_offset = 0xdbb8f,
        .vanilla_target_value = 0x1d,
        .vanilla_exterior_region = REGION_EXT_LW_DEATH_MOUNTAIN_SPIRAL_CAVE_TOP,
        .vanilla_interior_region = REGION_INT_LW_DEATH_MOUNTAIN_SPIRAL_CAVE_UPPER,
    },
    {
        .name = "Spiral Cave (Bottom)",
        .target_offset = 0xdbb8e,
        .vanilla_target_value = 0x1c,
        .vanilla_exterior_region = REGION_EXT_LW_DEATH_MOUNTAIN_LOWER,
        .vanilla_interior_region = REGION_INT_LW_DEATH_MOUNTAIN_SPIRAL_CAVE_LOWER,
    },
    {
        .name = "Superbunny Cave (Bottom)",
        .target_offset = 0xdbb85,
        .vanilla_target_value = 0x13,
        .vanilla_exterior_region = REGION_EXT_DW_DEATH_MOUNTAIN_LOWER_EAST,
        .vanilla_interior_region = REGION_INT_DW_DEATH_MOUNTAIN_SUPERBUNNY_CAVE_LOWER,
    },
    {
        .name = "Superbunny Cave (Top)",
        .target_offset = 0xdbb86,
        .vanilla_target_value = 0x14,
        .vanilla_exterior_region = REGION_EXT_DW_DEATH_MOUNTAIN_UPPER,
        .vanilla_interior_region = REGION_INT_DW_DEATH_MOUNTAIN_SUPERBUNNY_CAVE_UPPER,
    },
    {
        .name = "Swamp Palace",
        .target_offset = 0xdbb97,
        .vanilla_target_value = 0x25,
        .vanilla_exterior_region = REGION_EXT_DW_OVERWORLD,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "Tavern (Front)",
        .target_offset = 0xdbbb4,
        .vanilla_target_value = 0x42,
        .vanilla_exterior_region = REGION_EXT_LW_OVERWORLD,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "Tavern North",
        .target_offset = 0xdbbb5,
        .vanilla_target_value = 0x43,
        .vanilla_exterior_region = REGION_EXT_LW_OVERWORLD,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "Thieves Town",
        .target_offset = 0xdbba6,
        .vanilla_target_value = 0x34,
        .vanilla_exterior_region = REGION_EXT_DW_OVERWORLD,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "Tower of Hera",
        .target_offset = 0xdbba5,
        .vanilla_target_value = 0x33,
        .vanilla_exterior_region = REGION_EXT_LW_DEATH_MOUNTAIN_UPPER,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "Turtle Rock (Front)",
        .target_offset = 0xdbba7,
        .vanilla_target_value = 0x35,
        .vanilla_exterior_region = REGION_EXT_DW_DEATH_MOUNTAIN_UPPER,
        .vanilla_interior_region = REGION_INT_DW_TURTLE_ROCK,
    },
    {
        .name = "Turtle Rock Isolated Ledge",
        .target_offset = 0xdbb8a,
        .vanilla_target_value = 0x18,
        .vanilla_exterior_region = REGION_EXT_DW_DEATH_MOUNTAIN_TURTLE_ROCK_ISOLATED_LEDGE,
        .vanilla_interior_region = REGION_INT_DW_TURTLE_ROCK,
    },
    {
        .name = "Two Brothers House (East)",
        .target_offset = 0xdbb82,
        .vanilla_target_value = 0x10,
        .vanilla_exterior_region = REGION_EXT_LW_OVERWORLD,
        .vanilla_interior_region = REGION_INT_LW_TWO_BROTHERS_HOUSE,
    },
    {
        .name = "Two Brothers House (West)",
        .target_offset = 0xdbb81,
        .vanilla_target_value = 0xf,
        .vanilla_exterior_region = REGION_EXT_LW_OVERWORLD,
        .vanilla_interior_region = REGION_INT_LW_TWO_BROTHERS_HOUSE,
    },
    {
        .name = "Village of Outcasts Shop",
        .target_offset = 0xdbbd2,
        .vanilla_target_value = 0x60,
        .vanilla_exterior_region = REGION_EXT_DW_OVERWORLD,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
    {
        .name = "Waterfall of Wishing",
        .target_offset = 0xdbbce,
        .vanilla_target_value = 0x5c,
        .vanilla_exterior_region = REGION_EXT_LW_OVERWORLD,
        .vanilla_interior_region = REGION_INT_ISOLATED,
    },
};

const size_t num_entrances =
    sizeof(entrances) / sizeof(entrances[0]);

const interior_exit interior_exits[] = {
    {
        .name = "Agahnims Tower",
        .overworld_area_offset = 0x15bb1,
        .target_vram_location_offset = 0x15c25,
        .vanilla_overworld_area_value = 0x1b,
        .vanilla_target_vram_location_value = 0x32,
        .vanilla_exterior_region = REGION_EXT_LW_HYRULE_CASTLE_ROOF,
    },
    {
        .name = "Bat Cave Cave",
        .overworld_area_offset = 0x15b9e,
        .target_vram_location_offset = 0x15bff,
        .vanilla_overworld_area_value = 0x22,
        .vanilla_target_vram_location_value = 0x412,
        .vanilla_exterior_region = REGION_EXT_LW_OVERWORLD,
    },
    {
        .name = "Bumper Cave (Bottom)",
        .overworld_area_offset = 0x15ba3,
        .target_vram_location_offset = 0x15c09,
        .vanilla_overworld_area_value = 0x4a,
        .vanilla_target_vram_location_value = 0x3a0,
        .vanilla_exterior_region = REGION_EXT_DW_OVERWORLD,
    },
    {
        .name = "Bumper Cave (Top)",
        .overworld_area_offset = 0x15ba4,
        .target_vram_location_offset = 0x15c0b,
        .vanilla_overworld_area_value = 0x4a,
        .vanilla_target_vram_location_value = 0xa0,
        .vanilla_exterior_region = REGION_EXT_DW_BUMPER_CAVE_TOP,
    },
    {
        .name = "Death Mountain Return Cave (East)",
        .overworld_area_offset = 0x15bbc,
        .target_vram_location_offset = 0x15c3b,
        .vanilla_overworld_area_value = 0x3,
        .vanilla_target_vram_location_value = 0xd82,
        .vanilla_exterior_region = REGION_EXT_LW_DEATH_MOUNTAIN_LOWER,
    },
    {
        .name = "Death Mountain Return Cave (West)",
        .overworld_area_offset = 0x15bbb,
        .target_vram_location_offset = 0x15c39,
        .vanilla_overworld_area_value = 0xa,
        .vanilla_target_vram_location_value = 0xa0,
        .vanilla_exterior_region = REGION_EXT_LW_DEATH_MOUNTAIN_RETURN_LEDGE,
    },
    {
        .name = "Desert Palace (East)",
        .overworld_area_offset = 0x15b97,
        .target_vram_location_offset = 0x15bf1,
        .vanilla_overworld_area_value = 0x30,
        .vanilla_target_vram_location_value = 0x2a8,
        .vanilla_exterior_region = REGION_EXT_LW_DESERT_PALACE_EAST,
    },
    {
        .name = "Desert Palace (North)",
        .overworld_area_offset = 0x15b99,
        .target_vram_location_offset = 0x15bf5,
        .vanilla_overworld_area_value = 0x30,
        .vanilla_target_vram_location_value = 0x16,
        .vanilla_exterior_region = REGION_EXT_LW_DESERT_PALACE_LEDGE,
    },
    {
        .name = "Desert Palace (South)",
        .overworld_area_offset = 0x15b96,
        .target_vram_location_offset = 0x15bef,
        .vanilla_overworld_area_value = 0x30,
        .vanilla_target_vram_location_value = 0x314,
        .vanilla_exterior_region = REGION_EXT_LW_OVERWORLD,
    },
    {
        .name = "Desert Palace (West)",
        .overworld_area_offset = 0x15b98,
        .target_vram_location_offset = 0x15bf3,
        .vanilla_overworld_area_value = 0x30,
        .vanilla_target_vram_location_value = 0x280,
        .vanilla_exterior_region = REGION_EXT_LW_DESERT_PALACE_LEDGE,
    },
    {
        .name = "Eastern Palace",
        .overworld_area_offset = 0x15b95,
        .target_vram_location_offset = 0x15bed,
        .vanilla_overworld_area_value = 0x1e,
        .vanilla_target_vram_location_value = 0x5a,
        .vanilla_exterior_region = REGION_EXT_LW_OVERWORLD,
    },
    {
        .name = "Elder House (East)",
        .overworld_area_offset = 0x15b9b,
        .target_vram_location_offset = 0x15bf9,
        .vanilla_overworld_area_value = 0x18,
        .vanilla_target_vram_location_value = 0x2c4,
        .vanilla_exterior_region = REGION_EXT_LW_OVERWORLD,
    },
    {
        .name = "Elder House (West)",
        .overworld_area_offset = 0x15b9a,
        .target_vram_location_offset = 0x15bf7,
        .vanilla_overworld_area_value = 0x18,
        .vanilla_target_vram_location_value = 0x2bc,
        .vanilla_exterior_region = REGION_EXT_LW_OVERWORLD,
    },
    {
        .name = "Fairy Ascension Cave (Bottom)",
        .overworld_area_offset = 0x15ba7,
        .target_vram_location_offset = 0x15c11,
        .vanilla_overworld_area_value = 0x5,
        .vanilla_target_vram_location_value = 0xdd4,
        .vanilla_exterior_region = REGION_EXT_LW_DEATH_MOUNTAIN_LOWER,
    },
    {
        .name = "Fairy Ascension Cave (Top)",
        .overworld_area_offset = 0x15ba8,
        .target_vram_location_offset = 0x15c13,
        .vanilla_overworld_area_value = 0x5,
        .vanilla_target_vram_location_value = 0xad4,
        .vanilla_exterior_region = REGION_EXT_LW_DEATH_MOUNTAIN_FAIRY_ASCENSION_CAVE_TOP,
    },
    {
        .name = "Ganons Tower",
        .overworld_area_offset = 0x15bc4,
        .target_vram_location_offset = 0x15c4b,
        .vanilla_overworld_area_value = 0x43,
        .vanilla_target_vram_location_value = 0x52,
        .vanilla_exterior_region = REGION_EXT_DW_DEATH_MOUNTAIN_UPPER,
    },
    {
        .name = "Hookshot Cave (North)",
        .overworld_area_offset = 0x15bc8,
        .target_vram_location_offset = 0x15c53,
        .vanilla_overworld_area_value = 0x45,
        .vanilla_target_vram_location_value = 0x4c,
        .vanilla_exterior_region = REGION_EXT_DW_DEATH_MOUNTAIN_FLOATING_LEDGE,
    },
    {
        .name = "Hookshot Cave (South)",
        .overworld_area_offset = 0x15bc7,
        .target_vram_location_offset = 0x15c51,
        .vanilla_overworld_area_value = 0x45,
        .vanilla_target_vram_location_value = 0x4da,
        .vanilla_exterior_region = REGION_EXT_DW_DEATH_MOUNTAIN_UPPER,
    },
    {
        .name = "Hyrule Castle (East)",
        .overworld_area_offset = 0x15b90,
        .target_vram_location_offset = 0x15be3,
        .vanilla_overworld_area_value = 0x1b,
        .vanilla_target_vram_location_value = 0x4a,
        .vanilla_exterior_region = REGION_EXT_LW_HYRULE_CASTLE_ROOF,
    },
    {
        .name = "Hyrule Castle (South)",
        .overworld_area_offset = 0x15b8f,
        .target_vram_location_offset = 0x15be1,
        .vanilla_overworld_area_value = 0x1b,
        .vanilla_target_vram_location_value = 0x530,
        .vanilla_exterior_region = REGION_EXT_LW_OVERWORLD,
    },
    {
        .name = "Hyrule Castle (West)",
        .overworld_area_offset = 0x15b8e,
        .target_vram_location_offset = 0x15bdf,
        .vanilla_overworld_area_value = 0x1b,
        .vanilla_target_vram_location_value = 0x16,
        .vanilla_exterior_region = REGION_EXT_LW_HYRULE_CASTLE_ROOF,
    },
    {
        .name = "Hyrule Castle Secret Entrance",
        .overworld_area_offset = 0x15bbf,
        .target_vram_location_offset = 0x15c41,
        .vanilla_overworld_area_value = 0x1b,
        .vanilla_target_vram_location_value = 0x44a,
        .vanilla_exterior_region = REGION_EXT_LW_OVERWORLD,
    },
    {
        .name = "Ice Palace",
        .overworld_area_offset = 0x15bba,
        .target_vram_location_offset = 0x15c37,
        .vanilla_overworld_area_value = 0x75,
        .vanilla_target_vram_location_value = 0xbc6,
        .vanilla_exterior_region = REGION_EXT_DW_OUTSIDE_ICE_PALACE,
    },
    {
        .name = "Kakariko Well Cave",
        .overworld_area_offset = 0x15bc6,
        .target_vram_location_offset = 0x15c4f,
        .vanilla_overworld_area_value = 0x18,
        .vanilla_target_vram_location_value = 0x386,
        .vanilla_exterior_region = REGION_EXT_LW_OVERWORLD,
    },
    {
        .name = "Links House",
        .overworld_area_offset = 0x15b8c,
        .target_vram_location_offset = 0x15bdb,
        .vanilla_overworld_area_value = 0x2c,
        .vanilla_target_vram_location_value = 0x506,
        .vanilla_exterior_region = REGION_EXT_LW_OVERWORLD,
    },
    {
        .name = "Lost Woods Hideout Stump",
        .overworld_area_offset = 0x15bc2,
        .target_vram_location_offset = 0x15c47,
        .vanilla_overworld_area_value = 0x0,
        .vanilla_target_vram_location_value = 0xf4e,
        .vanilla_exterior_region = REGION_EXT_LW_LOST_WOODS,
    },
    {
        .name = "Lumberjack Tree Cave",
        .overworld_area_offset = 0x15b9f,
        .target_vram_location_offset = 0x15c01,
        .vanilla_overworld_area_value = 0x2,
        .vanilla_target_vram_location_value = 0x118,
        .vanilla_exterior_region = REGION_EXT_LW_OVERWORLD,
    },
    {
        .name = "Misery Mire",
        .overworld_area_offset = 0x15bb4,
        .target_vram_location_offset = 0x15c2b,
        .vanilla_overworld_area_value = 0x70,
        .vanilla_target_vram_location_value = 0x414,
        .vanilla_exterior_region = REGION_EXT_DW_MIRE,
    },
    {
        .name = "North Fairy Cave",
        .overworld_area_offset = 0x15bc5,
        .target_vram_location_offset = 0x15c4d,
        .vanilla_overworld_area_value = 0x15,
        .vanilla_target_vram_location_value = 0x88,
        .vanilla_exterior_region = REGION_EXT_LW_OVERWORLD,
    },
    {
        .name = "Old Man Cave (East)",
        .overworld_area_offset = 0x15b94,
        .target_vram_location_offset = 0x15beb,
        .vanilla_overworld_area_value = 0x3,
        .vanilla_target_vram_location_value = 0x1402,
        .vanilla_exterior_region = REGION_EXT_LW_DEATH_MOUNTAIN_LOWER,
    },
    {
        .name = "Old Man Cave (West)",
        .overworld_area_offset = 0x15b93,
        .target_vram_location_offset = 0x15be9,
        .vanilla_overworld_area_value = 0xa,
        .vanilla_target_vram_location_value = 0x3a0,
        .vanilla_exterior_region = REGION_EXT_LW_OVERWORLD,
    },
    {
        .name = "Old Man House (Bottom)",
        .overworld_area_offset = 0x15bbd,
        .target_vram_location_offset = 0x15c3d,
        .vanilla_overworld_area_value = 0x3,
        .vanilla_target_vram_location_value = 0x181a,
        .vanilla_exterior_region = REGION_EXT_LW_DEATH_MOUNTAIN_LOWER,
    },
    {
        .name = "Old Man House (Top)",
        .overworld_area_offset = 0x15bbe,
        .target_vram_location_offset = 0x15c3f,
        .vanilla_overworld_area_value = 0x3,
        .vanilla_target_vram_location_value = 0x10c6,
        .vanilla_exterior_region = REGION_EXT_LW_DEATH_MOUNTAIN_LOWER,
    },
    {
        .name = "Palace of Darkness",
        .overworld_area_offset = 0x15bb3,
        .target_vram_location_offset = 0x15c29,
        .vanilla_overworld_area_value = 0x5e,
        .vanilla_target_vram_location_value = 0x5a,
        .vanilla_exterior_region = REGION_EXT_DW_OVERWORLD,
    },
    {
        .name = "Paradox Cave (Bottom)",
        .overworld_area_offset = 0x15bab,
        .target_vram_location_offset = 0x15c19,
        .vanilla_overworld_area_value = 0x5,
        .vanilla_target_vram_location_value = 0xee0,
        .vanilla_exterior_region = REGION_EXT_LW_DEATH_MOUNTAIN_LOWER,
    },
    {
        .name = "Paradox Cave (Middle)",
        .overworld_area_offset = 0x15bac,
        .target_vram_location_offset = 0x15c1b,
        .vanilla_overworld_area_value = 0x5,
        .vanilla_target_vram_location_value = 0x17e0,
        .vanilla_exterior_region = REGION_EXT_LW_DEATH_MOUNTAIN_LOWER,
    },
    {
        .name = "Paradox Cave (Top)",
        .overworld_area_offset = 0x15bad,
        .target_vram_location_offset = 0x15c1d,
        .vanilla_overworld_area_value = 0x5,
        .vanilla_target_vram_location_value = 0x460,
        .vanilla_exterior_region = REGION_EXT_LW_DEATH_MOUNTAIN_UPPER,
    },
    {
        .name = "Pyramid (Ganon)",
        .overworld_area_offset = 0x15bc3,
        .target_vram_location_offset = 0x15c49,
        .vanilla_overworld_area_value = 0x5b,
        .vanilla_target_vram_location_value = 0xb0e,
        .vanilla_exterior_region = REGION_EXT_DW_OVERWORLD,
    },
    {
        .name = "Sanctuary",
        .overworld_area_offset = 0x15b8d,
        .target_vram_location_offset = 0x15bdd,
        .vanilla_overworld_area_value = 0x13,
        .vanilla_target_vram_location_value = 0x1c,
        .vanilla_exterior_region = REGION_EXT_LW_OVERWORLD,
    },
    {
        .name = "Skull Woods Final Section",
        .overworld_area_offset = 0x15bb8,
        .target_vram_location_offset = 0x15c33,
        .vanilla_overworld_area_value = 0x40,
        .vanilla_target_vram_location_value = 0x282,
        .vanilla_exterior_region = REGION_EXT_DW_LOST_WOODS_NORTH,
    },
    {
        .name = "Skull Woods First Section",
        .overworld_area_offset = 0x15bb7,
        .target_vram_location_offset = 0x15c31,
        .vanilla_overworld_area_value = 0x40,
        .vanilla_target_vram_location_value = 0xf4c,
        .vanilla_exterior_region = REGION_EXT_DW_LOST_WOODS_SOUTH,
    },
    {
        .name = "Skull Woods Second Section (East)",
        .overworld_area_offset = 0x15bb6,
        .target_vram_location_offset = 0x15c2f,
        .vanilla_overworld_area_value = 0x40,
        .vanilla_target_vram_location_value = 0xeb8,
        .vanilla_exterior_region = REGION_EXT_DW_LOST_WOODS_SOUTH,
    },
    {
        .name = "Skull Woods Second Section (West)",
        .overworld_area_offset = 0x15bb5,
        .target_vram_location_offset = 0x15c2d,
        .vanilla_overworld_area_value = 0x40,
        .vanilla_target_vram_location_value = 0xc8e,
        .vanilla_exterior_region = REGION_EXT_DW_LOST_WOODS_NORTH,
    },
    {
        .name = "Spectacle Rock Cave (Bottom)",
        .overworld_area_offset = 0x15bae,
        .target_vram_location_offset = 0x15c1f,
        .vanilla_overworld_area_value = 0x3,
        .vanilla_target_vram_location_value = 0xd9c,
        .vanilla_exterior_region = REGION_EXT_LW_DEATH_MOUNTAIN_SPECTACLE_ROCK_CAVE_LOWER,
    },
    {
        .name = "Spectacle Rock Cave (Peak)",
        .overworld_area_offset = 0x15bb0,
        .target_vram_location_offset = 0x15c23,
        .vanilla_overworld_area_value = 0x3,
        .vanilla_target_vram_location_value = 0x92c,
        .vanilla_exterior_region = REGION_EXT_LW_DEATH_MOUNTAIN_LOWER,
    },
    {
        .name = "Spectacle Rock Cave (Mid)",
        .overworld_area_offset = 0x15baf,
        .target_vram_location_offset = 0x15c21,
        .vanilla_overworld_area_value = 0x3,
        .vanilla_target_vram_location_value = 0xeac,
        .vanilla_exterior_region = REGION_EXT_LW_DEATH_MOUNTAIN_SPECTACLE_ROCK_CAVE_MID,
    },
    {
        .name = "Spiral Cave (Bottom)",
        .overworld_area_offset = 0x15ba9,
        .target_vram_location_offset = 0x15c15,
        .vanilla_overworld_area_value = 0x5,
        .vanilla_target_vram_location_value = 0xcca,
        .vanilla_exterior_region = REGION_EXT_LW_DEATH_MOUNTAIN_LOWER,
    },
    {
        .name = "Spiral Cave (Top)",
        .overworld_area_offset = 0x15baa,
        .target_vram_location_offset = 0x15c17,
        .vanilla_overworld_area_value = 0x5,
        .vanilla_target_vram_location_value = 0x7c8,
        .vanilla_exterior_region = REGION_EXT_LW_DEATH_MOUNTAIN_SPIRAL_CAVE_TOP,
    },
    {
        .name = "Superbunny Cave (Bottom)",
        .overworld_area_offset = 0x15ba0,
        .target_vram_location_offset = 0x15c03,
        .vanilla_overworld_area_value = 0x45,
        .vanilla_target_vram_location_value = 0xee0,
        .vanilla_exterior_region = REGION_EXT_DW_DEATH_MOUNTAIN_LOWER_EAST,
    },
    {
        .name = "Superbunny Cave (Top)",
        .overworld_area_offset = 0x15ba1,
        .target_vram_location_offset = 0x15c05,
        .vanilla_overworld_area_value = 0x45,
        .vanilla_target_vram_location_value = 0x460,
        .vanilla_exterior_region = REGION_EXT_DW_DEATH_MOUNTAIN_UPPER,
    },
    {
        .name = "Swamp Palace",
        .overworld_area_offset = 0x15bb2,
        .target_vram_location_offset = 0x15c27,
        .vanilla_overworld_area_value = 0x7b,
        .vanilla_target_vram_location_value = 0x49e,
        .vanilla_exterior_region = REGION_EXT_DW_OVERWORLD,
    },
    {
        .name = "Thieves Town",
        .overworld_area_offset = 0x15bc1,
        .target_vram_location_offset = 0x15c45,
        .vanilla_overworld_area_value = 0x58,
        .vanilla_target_vram_location_value = 0xb2e,
        .vanilla_exterior_region = REGION_EXT_DW_OVERWORLD,
    },
    {
        .name = "Tower of Hera",
        .overworld_area_offset = 0x15bb9,
        .target_vram_location_offset = 0x15c35,
        .vanilla_overworld_area_value = 0x3,
        .vanilla_target_vram_location_value = 0x50,
        .vanilla_exterior_region = REGION_EXT_LW_DEATH_MOUNTAIN_UPPER,
    },
    {
        .name = "Turtle Rock (Front)",
        .overworld_area_offset = 0x15bc0,
        .target_vram_location_offset = 0x15c43,
        .vanilla_overworld_area_value = 0x47,
        .vanilla_target_vram_location_value = 0x712,
        .vanilla_exterior_region = REGION_EXT_DW_DEATH_MOUNTAIN_UPPER,
    },
    {
        .name = "Turtle Rock Isolated Ledge",
        .overworld_area_offset = 0x15ba5,
        .target_vram_location_offset = 0x15c0d,
        .vanilla_overworld_area_value = 0x45,
        .vanilla_target_vram_location_value = 0xad4,
        .vanilla_exterior_region = REGION_EXT_DW_DEATH_MOUNTAIN_TURTLE_ROCK_ISOLATED_LEDGE,
    },
    {
        .name = "Turtle Rock Ledge (East)",
        .overworld_area_offset = 0x15ba6,
        .target_vram_location_offset = 0x15c0f,
        .vanilla_overworld_area_value = 0x45,
        .vanilla_target_vram_location_value = 0x7e0,
        .vanilla_exterior_region = REGION_EXT_DW_DEATH_MOUNTAIN_TURTLE_ROCK_LONG_LEDGE,
    },
    {
        .name = "Turtle Rock Ledge (West)",
        .overworld_area_offset = 0x15ba2,
        .target_vram_location_offset = 0x15c07,
        .vanilla_overworld_area_value = 0x45,
        .vanilla_target_vram_location_value = 0x7ca,
        .vanilla_exterior_region = REGION_EXT_DW_DEATH_MOUNTAIN_TURTLE_ROCK_LONG_LEDGE,
    },
    {
        .name = "Two Brothers House (East)",
        .overworld_area_offset = 0x15b9d,
        .target_vram_location_offset = 0x15bfd,
        .vanilla_overworld_area_value = 0x29,
        .vanilla_target_vram_location_value = 0x880,
        .vanilla_exterior_region = REGION_EXT_LW_OVERWORLD,
    },
    {
        .name = "Two Brothers House (West)",
        .overworld_area_offset = 0x15b9c,
        .target_vram_location_offset = 0x15bfb,
        .vanilla_overworld_area_value = 0x28,
        .vanilla_target_vram_location_value = 0x8a0,
        .vanilla_exterior_region = REGION_EXT_LW_OVERWORLD,
    },
};

const size_t num_interior_exits =
    sizeof(interior_exits) / sizeof(interior_exits[0]);

const hole holes[] = {
    {
        .name = "Bat Cave Drop",
        .target_offsets = { 0xdb859, 0xdb85a },
        .vanilla_target_value = 0x7e,
        .vanilla_target_name = "Bat Cave Cave",
        .vanilla_region = REGION_EXT_LW_OVERWORLD,
    },
    {
        .name = "Hyrule Castle Secret Entrance Drop",
        .target_offsets = { 0xdb858, -1 },
        .vanilla_target_value = 0x7d,
        .vanilla_target_name = "Hyrule Castle Secret Entrance",
        .vanilla_region = REGION_EXT_LW_OVERWORLD,
    },
    {
        .name = "Kakariko Well Drop",
        .target_offsets = { 0xdb85c, 0xdb85d },
        .vanilla_target_value = 0x80,
        .vanilla_target_name = "Kakariko Well Cave",
        .vanilla_region = REGION_EXT_LW_OVERWORLD,
    },
    {
        .name = "Lost Woods Hideout Drop",
        .target_offsets = { 0xdb853, -1 },
        .vanilla_target_value = 0x7a,
        .vanilla_target_name = "Lost Woods Hideout Stump",
        .vanilla_region = REGION_EXT_LW_LOST_WOODS,
    },
    {
        .name = "Lumberjack Tree Tree",
        .target_offsets = { 0xdb85b, -1 },
        .vanilla_target_value = 0x7f,
        .vanilla_target_name = "Lumberjack Tree Cave",
        .vanilla_region = REGION_EXT_LW_OVERWORLD,
    },
    {
        .name = "North Fairy Cave Drop",
        .target_offsets = { 0xdb857, -1 },
        .vanilla_target_value = 0x7c,
        .vanilla_target_name = "North Fairy Cave",
        .vanilla_region = REGION_EXT_LW_OVERWORLD,
    },
    {
        .name = "Pyramid Hole",
        .target_offsets = { 0xdb854, 0xdb855 },
        .vanilla_target_value = 0x7b,
        .vanilla_target_name = "Pyramid (Ganon)",
        .vanilla_region = REGION_EXT_DW_OVERWORLD,
    },
    {
        .name = "Sanctuary Grave",
        .target_offsets = { 0xdb85e, -1 },
        .vanilla_target_value = 0x81,
        .vanilla_target_name = "Hyrule Castle (South)",
        .vanilla_region = REGION_EXT_LW_OVERWORLD,
    },
    {
        .name = "Skull Woods First Section Hole (East)",
        .target_offsets = { 0xdb84f, 0xdb850 },
        .vanilla_target_value = 0x78,
        .vanilla_target_name = "Skull Woods First Section",
        .vanilla_region = REGION_EXT_DW_LOST_WOODS_SOUTH,
    },
    {
        .name = "Skull Woods First Section Hole (North)",
        .target_offsets = { 0xdb84c, -1 },
        .vanilla_target_value = 0x76,
        .vanilla_target_name = "Skull Woods First Section",
        .vanilla_region = REGION_EXT_DW_LOST_WOODS_SOUTH,
    },
    {
        .name = "Skull Woods First Section Hole (West)",
        .target_offsets = { 0xdb84d, 0xdb84e },
        .vanilla_target_value = 0x77,
        .vanilla_target_name = "Skull Woods First Section",
        .vanilla_region = REGION_EXT_DW_LOST_WOODS_SOUTH,
    },
    {
        .name = "Skull Woods Second Section Hole",
        .target_offsets = { 0xdb851, 0xdb852 },
        .vanilla_target_value = 0x79,
        .vanilla_target_name = "Skull Woods Second Section (West)",
        .vanilla_region = REGION_EXT_DW_LOST_WOODS_NORTH,
    },
};

const size_t num_holes =
    sizeof(holes) / sizeof(holes[0]);

const region_link region_links[] = {
    // Exterior

    {
        .origin_region = REGION_EXT_LW_OVERWORLD,
        .destination_region = REGION_EXT_DW_OVERWORLD,
        .method = "Teleport square",
    },
    {
        .origin_region = REGION_EXT_LW_OVERWORLD,
        .destination_region = REGION_EXT_DW_MIRE,
        .method = "Flute and teleport square",
    },
    {
        .origin_region = REGION_EXT_LW_OVERWORLD,
        .destination_region = REGION_EXT_DW_OUTSIDE_ICE_PALACE,
        .method = "Teleport square",
    },
    {
        .origin_region = REGION_EXT_LW_OVERWORLD,
        .destination_region = REGION_EXT_LW_LOST_WOODS,
        .method = "Walk in",
    },
    {
        .origin_region = REGION_EXT_LW_DEATH_MOUNTAIN_LOWER,
        .destination_region = REGION_EXT_DW_DEATH_MOUNTAIN_LOWER_WEST,
        .method = "Teleport square",
    },
    {
        .origin_region = REGION_EXT_LW_DEATH_MOUNTAIN_LOWER,
        .destination_region = REGION_EXT_DW_DEATH_MOUNTAIN_LOWER_EAST,
        .method = "Teleport square",
    },
    {
        .origin_region = REGION_EXT_LW_DEATH_MOUNTAIN_UPPER,
        .destination_region = REGION_EXT_DW_DEATH_MOUNTAIN_UPPER,
        .method = "Teleport square",
    },
    {
        .origin_region = REGION_EXT_LW_DEATH_MOUNTAIN_LOWER,
        .destination_region = REGION_EXT_LW_DEATH_MOUNTAIN_SPECTACLE_ROCK_CAVE_MID,
        .method = "Jump",
    },
    {
        .origin_region = REGION_EXT_LW_DEATH_MOUNTAIN_LOWER,
        .destination_region = REGION_EXT_LW_DEATH_MOUNTAIN_SPECTACLE_ROCK_CAVE_LOWER,
        .method = "Jump",
    },
    {
        .origin_region = REGION_EXT_LW_DEATH_MOUNTAIN_UPPER,
        .destination_region = REGION_EXT_LW_DEATH_MOUNTAIN_LOWER,
        .method = "Jump",
    },
    {
        .origin_region = REGION_EXT_LW_DEATH_MOUNTAIN_UPPER,
        .destination_region = REGION_EXT_LW_DEATH_MOUNTAIN_SPIRAL_CAVE_TOP,
        .method = "Jump",
    },
    {
        .origin_region = REGION_EXT_LW_DEATH_MOUNTAIN_UPPER,
        .destination_region = REGION_EXT_LW_DEATH_MOUNTAIN_FAIRY_ASCENSION_CAVE_TOP,
        .method = "Jump",
    },
    {
        .origin_region = REGION_EXT_LW_DEATH_MOUNTAIN_SPECTACLE_ROCK_CAVE_MID,
        .destination_region = REGION_EXT_LW_DEATH_MOUNTAIN_LOWER,
        .method = "Jump",
    },
    {
        .origin_region = REGION_EXT_LW_DEATH_MOUNTAIN_SPECTACLE_ROCK_CAVE_LOWER,
        .destination_region = REGION_EXT_LW_DEATH_MOUNTAIN_LOWER,
        .method = "Jump",
    },
    {
        .origin_region = REGION_EXT_LW_DEATH_MOUNTAIN_SPIRAL_CAVE_TOP,
        .destination_region = REGION_EXT_LW_DEATH_MOUNTAIN_LOWER,
        .method = "Jump",
    },
    {
        .origin_region = REGION_EXT_LW_DEATH_MOUNTAIN_FAIRY_ASCENSION_CAVE_TOP,
        .destination_region = REGION_EXT_LW_DEATH_MOUNTAIN_LOWER,
        .method = "Jump",
    },
    {
        .origin_region = REGION_EXT_LW_DEATH_MOUNTAIN_RETURN_LEDGE,
        .destination_region = REGION_EXT_LW_OVERWORLD,
        .method = "Jump",
    },
    {
        .origin_region = REGION_EXT_LW_HYRULE_CASTLE_ROOF,
        .destination_region = REGION_EXT_LW_OVERWORLD,
        .method = "Jump",
    },
    {
        .origin_region = REGION_EXT_LW_DESERT_PALACE_LEDGE,
        .destination_region = REGION_EXT_LW_OVERWORLD,
        .method = "Jump",
    },
    {
        .origin_region = REGION_EXT_LW_DESERT_PALACE_EAST,
        .destination_region = REGION_EXT_LW_OVERWORLD,
        .method = "Jump",
    },
    {
        .origin_region = REGION_EXT_LW_CAVE_45_LEDGE,
        .destination_region = REGION_EXT_LW_OVERWORLD,
        .method = "Jump",
    },
    {
        .origin_region = REGION_EXT_LW_CHECKERBOARD_CAVE_LEDGE,
        .destination_region = REGION_EXT_LW_OVERWORLD,
        .method = "Jump",
    },
    {
        .origin_region = REGION_EXT_LW_GRAVEYARD_CAVE_LEDGE,
        .destination_region = REGION_EXT_LW_OVERWORLD,
        .method = "Jump",
    },
    {
        .origin_region = REGION_EXT_DW_OVERWORLD,
        .destination_region = REGION_EXT_LW_OVERWORLD,
        .method = "Mirror",
    },
    {
        .origin_region = REGION_EXT_DW_OVERWORLD,
        .destination_region = REGION_EXT_LW_HYRULE_CASTLE_ROOF,
        .method = "Mirror",
    },
    {
        .origin_region = REGION_EXT_DW_OVERWORLD,
        .destination_region = REGION_EXT_LW_CAVE_45_LEDGE,
        .method = "Mirror",
    },
    {
        .origin_region = REGION_EXT_DW_OVERWORLD,
        .destination_region = REGION_EXT_LW_GRAVEYARD_CAVE_LEDGE,
        .method = "Mirror",
    },
    {
        .origin_region = REGION_EXT_DW_OVERWORLD,
        .destination_region = REGION_EXT_DW_LOST_WOODS_SOUTH,
        .method = "Walk in",
    },
    {
        .origin_region = REGION_EXT_DW_MIRE,
        .destination_region = REGION_EXT_LW_OVERWORLD,
        .method = "Mirror",
    },
    {
        .origin_region = REGION_EXT_DW_MIRE,
        .destination_region = REGION_EXT_LW_CHECKERBOARD_CAVE_LEDGE,
        .method = "Mirror",
    },
        {
        .origin_region = REGION_EXT_DW_BUMPER_CAVE_TOP,
        .destination_region = REGION_EXT_DW_OVERWORLD,
        .method = "Jump",
    },
    {
        .origin_region = REGION_EXT_DW_DEATH_MOUNTAIN_LOWER_WEST,
        .destination_region = REGION_EXT_DW_DEATH_MOUNTAIN_SPIKE_CAVE_LEDGE,
        .method = "Jump",
    },
    {
        .origin_region = REGION_EXT_DW_DEATH_MOUNTAIN_SPIKE_CAVE_LEDGE,
        .destination_region = REGION_EXT_DW_DEATH_MOUNTAIN_LOWER_WEST,
        .method = "Jump",
    },
    {
        .origin_region = REGION_EXT_DW_DEATH_MOUNTAIN_UPPER,
        .destination_region = REGION_EXT_DW_DEATH_MOUNTAIN_LOWER_WEST,
        .method = "Jump",
    },
    {
        .origin_region = REGION_EXT_DW_DEATH_MOUNTAIN_UPPER,
        .destination_region = REGION_EXT_DW_DEATH_MOUNTAIN_LOWER_EAST,
        .method = "Jump",
    },
    {
        .origin_region = REGION_EXT_DW_DEATH_MOUNTAIN_FLOATING_LEDGE,
        .destination_region = REGION_EXT_DW_DEATH_MOUNTAIN_UPPER,
        .method = "Jump",
    },
    {
        .origin_region = REGION_EXT_DW_DEATH_MOUNTAIN_TURTLE_ROCK_LONG_LEDGE,
        .destination_region = REGION_EXT_LW_DEATH_MOUNTAIN_MIMIC_CAVE_LEDGE,
        .method = "Mirror",
    },

    // Interior

    {
        .origin_region = REGION_INT_LW_DEATH_MOUNTAIN_SPIRAL_CAVE_UPPER,
        .destination_region = REGION_INT_LW_DEATH_MOUNTAIN_SPIRAL_CAVE_LOWER,
        .method = "Fall",
    },
    {
        .origin_region = REGION_INT_LW_DEATH_MOUNTAIN_SPECTACLE_ROCK_CAVE_LOWER,
        .destination_region = REGION_INT_LW_DEATH_MOUNTAIN_SPECTACLE_ROCK_CAVE_PEAK,
        .method = "Climb",
    },
    {
        .origin_region = REGION_INT_LW_DEATH_MOUNTAIN_SPECTACLE_ROCK_CAVE_PEAK,
        .destination_region = REGION_INT_LW_DEATH_MOUNTAIN_SPECTACLE_ROCK_CAVE_MID,
        .method = "Fall",
    },
    {
        .origin_region = REGION_INT_DW_DEATH_MOUNTAIN_SUPERBUNNY_CAVE_LOWER,
        .destination_region = REGION_INT_DW_DEATH_MOUNTAIN_SUPERBUNNY_CAVE_UPPER,
        .method = "Climb",
    },
    {
        .origin_region = REGION_INT_LW_HYRULE_CASTLE,
        .destination_region = REGION_INT_LW_SANCTUARY,
        .method = "Go through sewers",
    },
};

const size_t num_region_links =
    sizeof(region_links) / sizeof(region_links[0]);

const location_link location_links[] = {
    {
        .name = "Agahnims Tower",
        .entrances_offset = 2,
        .interior_exits_offset = 0,
    },
    {
        .name = "Bat Cave Cave",
        .entrances_offset = 5,
        .interior_exits_offset = 1,
    },
    {
        .name = "Bumper Cave (Bottom)",
        .entrances_offset = 13,
        .interior_exits_offset = 2,
    },
    {
        .name = "Bumper Cave (Top)",
        .entrances_offset = 14,
        .interior_exits_offset = 3,
    },
    {
        .name = "Death Mountain Return Cave (East)",
        .entrances_offset = 39,
        .interior_exits_offset = 4,
    },
    {
        .name = "Death Mountain Return Cave (West)",
        .entrances_offset = 40,
        .interior_exits_offset = 5,
    },
    {
        .name = "Desert Palace (East)",
        .entrances_offset = 42,
        .interior_exits_offset = 6,
    },
    {
        .name = "Desert Palace (North)",
        .entrances_offset = 43,
        .interior_exits_offset = 7,
    },
    {
        .name = "Desert Palace (South)",
        .entrances_offset = 44,
        .interior_exits_offset = 8,
    },
    {
        .name = "Desert Palace (West)",
        .entrances_offset = 45,
        .interior_exits_offset = 9,
    },
    {
        .name = "Eastern Palace",
        .entrances_offset = 47,
        .interior_exits_offset = 10,
    },
    {
        .name = "Elder House (East)",
        .entrances_offset = 48,
        .interior_exits_offset = 11,
    },
    {
        .name = "Elder House (West)",
        .entrances_offset = 49,
        .interior_exits_offset = 12,
    },
    {
        .name = "Fairy Ascension Cave (Bottom)",
        .entrances_offset = 50,
        .interior_exits_offset = 13,
    },
    {
        .name = "Fairy Ascension Cave (Top)",
        .entrances_offset = 51,
        .interior_exits_offset = 14,
    },
    {
        .name = "Ganons Tower",
        .entrances_offset = 54,
        .interior_exits_offset = 15,
    },
    {
        .name = "Hookshot Cave (North)",
        .entrances_offset = 58,
        .interior_exits_offset = 16,
    },
    {
        .name = "Hookshot Cave (South)",
        .entrances_offset = 57,
        .interior_exits_offset = 17,
    },
    {
        .name = "Hyrule Castle (East)",
        .entrances_offset = 61,
        .interior_exits_offset = 18,
    },
    {
        .name = "Hyrule Castle (South)",
        .entrances_offset = 62,
        .interior_exits_offset = 19,
    },
    {
        .name = "Hyrule Castle (West)",
        .entrances_offset = 63,
        .interior_exits_offset = 20,
    },
    {
        .name = "Hyrule Castle Secret Entrance",
        .entrances_offset = 64,
        .interior_exits_offset = 21,
    },
    {
        .name = "Ice Palace",
        .entrances_offset = 65,
        .interior_exits_offset = 22,
    },
    {
        .name = "Kakariko Well Cave",
        .entrances_offset = 69,
        .interior_exits_offset = 23,
    },
    {
        .name = "Links House",
        .entrances_offset = 76,
        .interior_exits_offset = 24,
    },
    {
        .name = "Lost Woods Hideout Stump",
        .entrances_offset = 79,
        .interior_exits_offset = 25,
    },
    {
        .name = "Lumberjack Tree Cave",
        .entrances_offset = 81,
        .interior_exits_offset = 26,
    },
    {
        .name = "Misery Mire",
        .entrances_offset = 85,
        .interior_exits_offset = 27,
    },
    {
        .name = "North Fairy Cave",
        .entrances_offset = 86,
        .interior_exits_offset = 28,
    },
    {
        .name = "Old Man Cave (East)",
        .entrances_offset = 87,
        .interior_exits_offset = 29,
    },
    {
        .name = "Old Man Cave (West)",
        .entrances_offset = 88,
        .interior_exits_offset = 30,
    },
    {
        .name = "Old Man House (Bottom)",
        .entrances_offset = 89,
        .interior_exits_offset = 31,
    },
    {
        .name = "Old Man House (Top)",
        .entrances_offset = 90,
        .interior_exits_offset = 32,
    },
    {
        .name = "Palace of Darkness",
        .entrances_offset = 91,
        .interior_exits_offset = 33,
    },
    {
        .name = "Paradox Cave (Bottom)",
        .entrances_offset = 93,
        .interior_exits_offset = 34,
    },
    {
        .name = "Paradox Cave (Middle)",
        .entrances_offset = 94,
        .interior_exits_offset = 35,
    },
    {
        .name = "Paradox Cave (Top)",
        .entrances_offset = 95,
        .interior_exits_offset = 36,
    },
    {
        .name = "Pyramid (Ganon)",
        .entrances_offset = 97,
        .interior_exits_offset = 37,
    },
    {
        .name = "Sanctuary",
        .entrances_offset = 101,
        .interior_exits_offset = 38,
    },
    {
        .name = "Skull Woods Final Section",
        .entrances_offset = 103,
        .interior_exits_offset = 39,
    },
    {
        .name = "Skull Woods First Section",
        .entrances_offset = 104,
        .interior_exits_offset = 40,
    },
    {
        .name = "Skull Woods Second Section (East)",
        .entrances_offset = 105,
        .interior_exits_offset = 41,
    },
    {
        .name = "Skull Woods Second Section (West)",
        .entrances_offset = 106,
        .interior_exits_offset = 42,
    },
    {
        .name = "Spectacle Rock Cave (Bottom)",
        .entrances_offset = 110,
        .interior_exits_offset = 43,
    },
    {
        .name = "Spectacle Rock Cave (Peak)",
        .entrances_offset = 111,
        .interior_exits_offset = 44,
    },
    {
        .name = "Spectacle Rock Cave (Mid)",
        .entrances_offset = 109,
        .interior_exits_offset = 45,
    },
    {
        .name = "Spiral Cave (Bottom)",
        .entrances_offset = 114,
        .interior_exits_offset = 46,
    },
    {
        .name = "Spiral Cave (Top)",
        .entrances_offset = 113,
        .interior_exits_offset = 47,
    },
    {
        .name = "Superbunny Cave (Bottom)",
        .entrances_offset = 115,
        .interior_exits_offset = 48,
    },
    {
        .name = "Superbunny Cave (Top)",
        .entrances_offset = 116,
        .interior_exits_offset = 49,
    },
    {
        .name = "Swamp Palace",
        .entrances_offset = 117,
        .interior_exits_offset = 50,
    },
    {
        .name = "Thieves Town",
        .entrances_offset = 120,
        .interior_exits_offset = 51,
    },
    {
        .name = "Tower of Hera",
        .entrances_offset = 121,
        .interior_exits_offset = 52,
    },
    {
        .name = "Turtle Rock (Front)",
        .entrances_offset = 122,
        .interior_exits_offset = 53,
    },
    {
        .name = "Turtle Rock Isolated Ledge",
        .entrances_offset = 123,
        .interior_exits_offset = 54,
    },
    {
        .name = "Turtle Rock Ledge (East)",
        .entrances_offset = 26,
        .interior_exits_offset = 55,
    },
    {
        .name = "Turtle Rock Ledge (West)",
        .entrances_offset = 27,
        .interior_exits_offset = 56,
    },
    {
        .name = "Two Brothers House (East)",
        .entrances_offset = 124,
        .interior_exits_offset = 57,
    },
    {
        .name = "Two Brothers House (West)",
        .entrances_offset = 125,
        .interior_exits_offset = 58,
    },
};

const size_t num_location_links =
    sizeof(location_links) / sizeof(location_links[0]);
